package recordings

import (
	"context"
	"errors"
	"os"
	"sync"
	"time"

	"github.com/HallelujahHomeChurch/hhc-cli/internal/api"
	"github.com/HallelujahHomeChurch/hhc-cli/internal/media"
)

var ErrPackageFailed = errors.New("package_failed")
var ErrSessionExpired = errors.New("session_expired")

// TransferProgress is ephemeral transport diagnostics, never remote readiness.
// Resumed progress includes server-confirmed objects, not just this invocation.
type TransferProgress struct {
	CompletedBytes int64
	TotalBytes     int64
	State          string
}

type UploadResult struct {
	OperationID              string                   `json:"operationId"`
	Package                  api.Package              `json:"-"`
	Publication              *api.PublishResult       `json:"publication,omitempty"`
	RecordingID              string                   `json:"recordingId,omitempty"`
	PackageID                string                   `json:"packageId,omitempty"`
	PackageDigest            string                   `json:"packageDigest,omitempty"`
	SizeBytes                int64                    `json:"sizeBytes"`
	SourceFingerprint        *media.SourceFingerprint `json:"sourceFingerprint"`
	Encoding                 *media.EncodingSummary   `json:"encoding,omitempty"`
	PrepareState             string                   `json:"prepareState"`
	TransferState            string                   `json:"transferState"`
	ValidationState          string                   `json:"validationState"`
	PublicationState         string                   `json:"publicationState"`
	RequestedActionSatisfied bool                     `json:"requestedActionSatisfied"`
	LocalCleanupState        string                   `json:"localCleanupState"`
	CleanupBytesRemaining    *int64                   `json:"cleanupBytesRemaining"`
}

// UploadPrepared also resumes an existing operation. Only remote status decides
// which objects need transfer; a successful PUT or complete response is not ready.
// User-owned input is never cleaned by this function.
func UploadPrepared(ctx context.Context, c *api.Client, u *Uploader, j *Journal) (UploadResult, error) {
	if _, bounded := ctx.Deadline(); !bounded {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, 4*time.Hour)
		defer cancel()
	}
	state := j.State()
	result := UploadResult{OperationID: state.OperationID, PrepareState: "not_applicable", TransferState: "unknown", ValidationState: "unknown", PublicationState: "unknown", LocalCleanupState: "not_applicable"}
	p := c.Principal()
	if state.Intent.Command != "upload" || p.Type != state.Intent.PrincipalType || p.ID != state.Intent.PrincipalID || p.ClientID != state.Intent.ClientID {
		return result, ErrOperationConflict
	}
	scopes := []string{"cms:recordings:read", "cms:recordings:write"}
	if state.Intent.Publish {
		scopes = append(scopes, "cms:recordings:publish")
	}
	if err := c.RequireScopes(scopes...); err != nil {
		return result, err
	}
	if state.Intent.Prepare {
		result.PrepareState, result.LocalCleanupState = "pending", "pending"
		result.RecordingID, result.PackageID, result.PackageDigest, result.SizeBytes = state.RecordingID, state.PackageID, state.PackageDigest, state.PackageBytes
		if state.SourceFingerprint.SHA256 != "" {
			result.SourceFingerprint = &state.SourceFingerprint
		}
		// A previous invocation may already have removed all generated bytes.
		// Query the authority before opening source, bundle or local package.
		for delay := 2 * time.Second; state.PackageID != ""; delay = min(30*time.Second, delay*2) {
			pkg, err := retryControl(ctx, func() (api.Package, error) { return c.PackageStatus(ctx, state.RecordingID, state.PackageID, "") })
			if err != nil {
				return result, err
			}
			result.Package = pkg
			if pkg.State == "ready" {
				return finishReady(ctx, c, j, result)
			}
			if pkg.State == "failed" {
				result.ValidationState = "failed"
				return result, ErrPackageFailed
			}
			if pkg.State == "expired" {
				return result, ErrSessionExpired
			}
			if pkg.State == "uploading" {
				break
			}
			if pkg.State != "freezing" && pkg.State != "validating" {
				return result, api.ErrInvalidResponse
			}
			result.TransferState, result.ValidationState = "complete", pkg.State
			if j.TransferProgress != nil {
				j.TransferProgress(TransferProgress{State: pkg.State})
			}
			if err := waitContext(ctx, delay); err != nil {
				return result, err
			}
		}
	}
	input, err := preparedInput(ctx, j)
	if err != nil {
		return result, err
	}
	state = j.State()
	result.Encoding = state.Encoding
	inv, err := media.ReadPackage(ctx, input)
	if err != nil {
		return result, err
	}
	state.PackageDigest = inv.InventoryDigest
	result.PackageDigest = inv.InventoryDigest
	result.SizeBytes, _ = media.ValidateRecordingInventory(inv)
	state.PackageBytes = result.SizeBytes
	if state.Intent.Prepare {
		result.PrepareState = "complete"
		result.SourceFingerprint = &state.SourceFingerprint
	}
	if err := j.Save(state); err != nil {
		return result, err
	}
	if state.RecordingID == "" {
		r, err := retryControl(ctx, func() (api.Recording, error) {
			return c.CreateRecording(ctx, state.Intent.Title, state.OperationID+":create")
		})
		if err != nil {
			return result, err
		}
		state.RecordingID = r.ID
		if err := j.Save(state); err != nil {
			return result, err
		}
	}
	if state.PackageID == "" {
		pkg, err := retryControl(ctx, func() (api.Package, error) {
			return c.CreatePackage(ctx, state.RecordingID, inv, state.OperationID+":package")
		})
		if err != nil {
			return result, err
		}
		state.PackageID, state.SessionID = pkg.PackageID, pkg.SessionID
		state.SessionExpiresAt = pkg.ExpiresAt
		if err := j.Save(state); err != nil {
			return result, err
		}
	}
	objects := make(map[string]media.RecordingPackageObject, len(inv.Objects))
	var transferBytes int64
	result.RecordingID, result.PackageID = state.RecordingID, state.PackageID
	for _, object := range inv.Objects {
		objects[object.Path] = object
		transferBytes += object.SizeBytes
	}
	root, err := os.OpenRoot(input)
	if err != nil {
		return result, err
	}
	defer root.Close()
	completionAccepted := false
	retries := 0
	resigned := false
	pollDelay := 2 * time.Second
reconcile:
	for {
		pkg, confirmed, err := confirmedPackage(ctx, c, state, objects)
		if err != nil {
			return result, err
		}
		result.Package = pkg
		if state.SessionExpiresAt.IsZero() || pkg.ExpiresAt.Before(state.SessionExpiresAt) {
			state.SessionExpiresAt = pkg.ExpiresAt
		}
		if err := j.Save(state); err != nil {
			return result, err
		}
		switch pkg.State {
		case "ready":
			root.Close() // Release Windows directory handle before owned cleanup.
			return finishReady(ctx, c, j, result)
		case "failed":
			result.ValidationState = "failed"
			return result, ErrPackageFailed
		case "expired":
			return result, ErrSessionExpired
		case "uploading":
			result.TransferState = "uploading"
			if completionAccepted {
				return result, api.ErrInvalidResponse
			}
			if !time.Now().Before(pkg.ExpiresAt) {
				return result, ErrSessionExpired
			}
			var accepted func(string)
			if j.TransferProgress != nil {
				var transferred int64
				for path := range confirmed {
					transferred += objects[path].SizeBytes
				}
				j.TransferProgress(TransferProgress{transferred, transferBytes, "uploading"})
				var progressMu sync.Mutex
				accepted = func(path string) {
					progressMu.Lock()
					defer progressMu.Unlock()
					if !confirmed[path] {
						confirmed[path] = true
						transferred += objects[path].SizeBytes
						j.TransferProgress(TransferProgress{transferred, transferBytes, "uploading"})
					}
				}
			}
			missing := make([]string, 0, len(objects)-len(confirmed))
			for _, object := range inv.Objects {
				if !confirmed[object.Path] {
					missing = append(missing, object.Path)
				}
			}
			for start := 0; start < len(missing); start += 100 {
				signed, err := retryControl(ctx, func() ([]api.SignedObject, error) {
					return c.SignPackage(ctx, state.RecordingID, state.PackageID, missing[start:min(start+100, len(missing))])
				})
				if err != nil {
					return result, err
				}
				if err := uploadBatch(ctx, u, root, state.PackageID, objects, signed, accepted); err != nil {
					if errors.Is(err, ErrUploadURLRejected) && !resigned {
						resigned = true
						continue reconcile
					}
					if transient(err) && retries < 2 {
						if waitErr := waitRetry(ctx, err, retries); waitErr != nil {
							return result, waitErr
						}
						retries++
						continue reconcile
					}
					return result, err
				}
			}
			if _, err := c.CompletePackage(ctx, state.RecordingID, state.PackageID); err != nil {
				if transient(err) && retries < 2 {
					if waitErr := waitRetry(ctx, err, retries); waitErr != nil {
						return result, waitErr
					}
					retries++
					continue reconcile
				}
				return result, err
			}
			completionAccepted = true
			continue // Query immediately; completion itself never establishes ready.
		case "freezing", "validating":
			result.TransferState = "complete"
			result.ValidationState = pkg.State
			if j.TransferProgress != nil {
				j.TransferProgress(TransferProgress{transferBytes, transferBytes, pkg.State})
			}
			if err := waitContext(ctx, pollDelay); err != nil {
				return result, err
			}
			pollDelay = min(30*time.Second, pollDelay*2)
		default:
			return result, api.ErrInvalidResponse
		}
	}
}

func finishReady(ctx context.Context, c *api.Client, j *Journal, result UploadResult) (value UploadResult, err error) {
	if result.Package.State != "ready" || result.Package.MediaExpiresAt == nil || !time.Now().Before(*result.Package.MediaExpiresAt) {
		return result, ErrSessionExpired
	}
	defer func() {
		state := j.State()
		state.LastResult = &value
		if saveErr := j.Save(state); saveErr != nil {
			value.RequestedActionSatisfied = false
			err = errors.Join(err, saveErr)
		}
	}()
	result.TransferState, result.ValidationState = "complete", "ready"
	result.Encoding = j.state.Encoding
	if j.state.Intent.Prepare {
		result.PrepareState = "complete"
		if err := j.cleanGenerated(); err != nil {
			result.LocalCleanupState = "failed"
			// Unknown after partial removal is null, never a misleading zero.
			result.CleanupBytesRemaining = nil
			return result, errors.Join(media.ErrLocalCleanup, err)
		}
		zero := int64(0)
		result.LocalCleanupState, result.CleanupBytesRemaining = "complete", &zero
	}
	if j.state.Intent.Publish {
		published, err := Publish(ctx, c, j)
		if published.Outcome != "" {
			result.Publication, result.PublicationState = &published, published.Outcome
		}
		if err != nil {
			return result, err
		}
	}
	result.RequestedActionSatisfied = true
	return result, nil
}

func confirmedPackage(ctx context.Context, c *api.Client, state JournalState, objects map[string]media.RecordingPackageObject) (api.Package, map[string]bool, error) {
	confirmed := make(map[string]bool)
	cursor := ""
	for {
		pkg, err := retryControl(ctx, func() (api.Package, error) { return c.PackageStatus(ctx, state.RecordingID, state.PackageID, cursor) })
		if err != nil {
			return api.Package{}, nil, err
		}
		if pkg.State != "uploading" {
			return pkg, nil, nil
		}
		for _, path := range pkg.ConfirmedObjects {
			if _, exists := objects[path]; !exists || confirmed[path] {
				return api.Package{}, nil, api.ErrInvalidResponse
			}
			confirmed[path] = true
		}
		if pkg.NextCursor == "" {
			return pkg, confirmed, nil
		}
		_, knownCursor := objects[pkg.NextCursor]
		if !knownCursor || pkg.NextCursor <= cursor || len(confirmed) > len(objects) {
			return api.Package{}, nil, api.ErrInvalidResponse
		}
		cursor = pkg.NextCursor
	}
}

func uploadBatch(ctx context.Context, u *Uploader, root *os.Root, pkg string, objects map[string]media.RecordingPackageObject, signed []api.SignedObject, accepted func(string)) error {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	jobs := make(chan api.SignedObject)
	errorsOut := make(chan error, 3)
	var workers sync.WaitGroup
	for range 3 {
		workers.Go(func() {
			for target := range jobs {
				info, err := root.Lstat(target.Path)
				if err == nil && !info.Mode().IsRegular() {
					err = ErrPackageChanged
				}
				if err == nil {
					var f *os.File
					f, err = root.Open(target.Path)
					if err == nil {
						opened, statErr := f.Stat()
						if statErr != nil || !os.SameFile(info, opened) {
							err = ErrPackageChanged
						} else {
							err = u.Put(ctx, f, pkg, objects[target.Path], target)
						}
						f.Close()
					}
				}
				if err != nil {
					errorsOut <- err
					cancel()
					return
				}
				if accepted != nil {
					accepted(target.Path)
				}
			}
		})
	}
dispatch:
	for _, target := range signed {
		select {
		case jobs <- target:
		case <-ctx.Done():
			break dispatch
		}
	}
	close(jobs)
	workers.Wait()
	close(errorsOut)
	for err := range errorsOut {
		if !errors.Is(err, context.Canceled) {
			return err
		}
	}
	return ctx.Err()
}
