package recordings

import (
	"os"
	"path/filepath"
	"testing"
)

func TestManagedWorkspaceCleanupPreservesSourceAndRejectsSymlinks(t *testing.T) {
	intent := journalIntent(t)
	if err := os.WriteFile(intent.Input, []byte("original"), 0600); err != nil {
		t.Fatal(err)
	}
	j, err := OpenJournal(t.TempDir(), journalFixtureID, &intent)
	if err != nil {
		t.Fatal(err)
	}
	defer j.Close()
	directory, err := j.generatedWorkspace()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "temporary"), []byte("hls"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := j.cleanGenerated(); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(directory); !os.IsNotExist(err) {
		t.Fatal("generated bytes retained")
	}
	if b, err := os.ReadFile(intent.Input); err != nil || string(b) != "original" {
		t.Fatal("source modified")
	}
	if err := os.Symlink(filepath.Dir(intent.Input), directory); err != nil {
		t.Skip("symlink unavailable")
	}
	if err := j.cleanGenerated(); err == nil {
		t.Fatal("accepted redirected workspace")
	}
	if b, err := os.ReadFile(intent.Input); err != nil || string(b) != "original" {
		t.Fatal("symlink target modified")
	}
}

func TestUnownedWorkspaceIsNeverAdoptedOrDeleted(t *testing.T) {
	intent := journalIntent(t)
	j, err := OpenJournal(t.TempDir(), journalFixtureID, &intent)
	if err != nil {
		t.Fatal(err)
	}
	defer j.Close()
	directory := filepath.Join(j.directory, "generated")
	if err := os.Mkdir(directory, 0700); err != nil {
		t.Fatal(err)
	}
	if _, err := j.generatedWorkspace(); err == nil {
		t.Fatal("adopted unowned directory")
	}
	if err := j.cleanGenerated(); err == nil {
		t.Fatal("deleted unowned directory")
	}
	if _, err := os.Stat(directory); err != nil {
		t.Fatal("lost unowned directory")
	}
}
