package recordings

import (
	"os"
	"path/filepath"
	"testing"
)

func TestManagedWorkspaceCleanupPreservesSourceAndRejectsSymlinks(t *testing.T) {
	intent := journalIntent(t)
	if err := os.WriteFile(intent.Input, []byte("original"), 0600); err != nil {
		t.Fatal(err)
	}
	j, err := OpenJournal(t.TempDir(), journalFixtureID, &intent)
	if err != nil {
		t.Fatal(err)
	}
	defer j.Close()
	directory, err := j.generatedWorkspace()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "temporary"), []byte("hls"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := j.cleanGenerated(); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(directory); !os.IsNotExist(err) {
		t.Fatal("generated bytes retained")
	}
	if b, err := os.ReadFile(intent.Input); err != nil || string(b) != "original" {
		t.Fatal("source modified")
	}
	if err := os.Symlink(filepath.Dir(intent.Input), directory); err != nil {
		t.Skip("symlink unavailable")
	}
	if err := j.cleanGenerated(); err == nil {
		t.Fatal("accepted redirected workspace")
	}
	if b, err := os.ReadFile(intent.Input); err != nil || string(b) != "original" {
		t.Fatal("symlink target modified")
	}
}

func TestUnownedWorkspaceIsNeverAdoptedOrDeleted(t *testing.T) {
	intent := journalIntent(t)
	j, err := OpenJournal(t.TempDir(), journalFixtureID, &intent)
	if err != nil {
		t.Fatal(err)
	}
	defer j.Close()
	directory := filepath.Join(j.directory, "generated")
	if err := os.Mkdir(directory, 0700); err != nil {
		t.Fatal(err)
	}
	if _, err := j.generatedWorkspace(); err == nil {
		t.Fatal("adopted unowned directory")
	}
	if err := j.cleanGenerated(); err == nil {
		t.Fatal("deleted unowned directory")
	}
	if _, err := os.Stat(directory); err != nil {
		t.Fatal("lost unowned directory")
	}
}

func TestStandaloneWorkspaceOnOutputVolumePreservesUserOutput(t *testing.T) {
	parent := t.TempDir()
	intent := Intent{Command: "prepare", Input: filepath.Join(parent, "source.mp4"), Output: filepath.Join(parent, "package"), VideoBitrate720: 1500000, VideoBitrate1080: 3000000}
	for _, path := range []string{intent.Input, intent.Output} {
		if err := os.WriteFile(path, []byte("preserve"), 0600); err != nil {
			t.Fatal(err)
		}
	}
	j, err := OpenJournal(t.TempDir(), journalFixtureID, &intent)
	if err != nil {
		t.Fatal(err)
	}
	defer j.Close()
	directory, err := j.generatedWorkspace()
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Dir(directory) != parent || directory == intent.Output {
		t.Fatal("not an isolated output-volume workspace")
	}
	if err := j.cleanGenerated(); err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{intent.Input, intent.Output} {
		if b, err := os.ReadFile(path); err != nil || string(b) != "preserve" {
			t.Fatal("modified user file")
		}
	}
}
